### PR TITLE
Upgrade solr/elastic to latest versions. Remove deprecated type

### PR DESCRIPTION
**Pull request by worleydl**
Update to shiny new versions of elastic and solr.

Solr required a path change in the Dockerfile, otherwise no issues.
Elastic required a configuration change and removal of `type` from the client code and schema.

Passes the run_most_notebooks tests.

**Note**:   If you have an existing environment, this requires a docker image rebuild and refreshing your python dependencies with a `pip install -r requirements.txt`

### CODE REVIEW

**Comment by worleydl** [comment]
Also needed to update the content type for JSON as it would break splainer with the new security policies that rolled out in 8.4.1

**Comment by epugh** [comment]
Awesome

**Comment by epugh** [comment]
We need to change up Solr defaults.

**Comment by epugh** [comment]
I could merge a pr ;-)

**Comment by softwaredoug** [comment]
Yep tests pass for me too. Great job! Yay tests.

Going to send a PR in for a test shell script to run, with a standard output saying whether tests passed / failed we can paste here... similar to the Solr releases

**Pull request merged**
