### PR TITLE
Reorganize notebooks into sub directories

### PR DESCRIPTION
**Pull request by softwaredoug**
Move all notebooks to a subfolder 

```
/notebooks/<search_engine>/<collection>
```

- Make sure they run using the ltr module (requiring an ltr module hook...)
- Each collection now has it's own data directory for its own data resources
- Each collection's config is now placed in the directory to change/modify the underlying Solr or Elasticsearch config for experimentation

(Under another PR I will use this to create tests for each notebook, but wanted to get this done first)

### CODE REVIEW

**Comment by worleydl** [comment]
Did you run into any issues building the solr docker image?

I run into the following with docker-compose 1.24.1:
```
ERROR: Service 'solr' failed to build: ADD failed: Forbidden path outside the build context: ../notebooks/solr/tmdb/solr_config ()
```

**Comment by softwaredoug** [comment]
Hmm I have 1.25.1 not getting that, but let me research a bit

**Comment by softwaredoug** [comment]
Looks like it's disallowed to recurse up in the docs. Not sure why it's working for me.

One solution might be to bundle docker-compose, etc under the "solr" directory under "notebooks". The nice thing about this is now everything is bundled under one hierarchy (except for the ltr library)

Basically now you would do 

```
cd notebooks/solr
docker-compose up
```

And you'd have a Solr with all the nested collections

Let me know what you think about that. Just pushed it up to get your feedback

**Comment by worleydl** [comment]
I think that should work...I'm not seeing a `docker-compose.yml` file under notebooks/solr, is that missing?

Also we'd need to modify the "all-in-one" compose under `docker/docker-compose.yml` to use this new path if possible.

**Comment by softwaredoug** [comment]
Oops! try again with the Solr one

**Comment by softwaredoug** [comment]
I think this is good to go @worleydl ... please kick the tires and make sure all the instructions in the Readme work for you

**Review by worleydl — APPROVED** [review]
All docker environments are working for me now and the docs look good 👍

**Pull request merged**
