### PR TITLE
Refactor/explicitize 2

### PR DESCRIPTION
**Pull request by softwaredoug**
Another PR refactoring the Hello LTR API for readability and ease of use purposes (for book)

## Judgments Reading

Instead of concerning the user with file-io, create a way to open judgments directly into a judgments list, using a context manager.

IE instead of

```
with open('judgments.txt') as f:
    judgments=judgments_from_file(f)
    # Do stuff with judgments
```

Collapses down to a more concise:

```
with judgments_open('judgments.txt') as judgments:
    # Do stuff with judgments
```

The latter is safer, as judgments is a generator, looping over the underlying file. The former you might save off `judgments`, thinking its a list, and then later when you read it it throws an exception that the file is not found. See [this blog article](https://opensourceconnections.com/blog/2020/06/10/python-generators-and-context-managers/)

It also saves a lot of boilerplate code...

## More readable feature logging

Use a `FeatureLogger` class to build up judgments. Feature Logging now looks like:

```
ftr_logger=FeatureLogger(client, index='tmdb', feature_set='genome')
with judgments_open('data/genome_judgments.txt') as judgment_list:
    for qid, query_judgments in groupby(judgment_list, key=lambda j: j.qid):
        ftr_logger.log_for_qid(judgments=query_judgments, 
                                             qid=qid,
                                             keywords=judgment_list.keywords(qid))
```

And ftr_logger internally has a logged that are all the judgments built up

## Ranklib training 

* Rename the 'train' module to 'ranklib' so it's obvious it does ranklib under the hood. 
* Now takes a `training_set` param, which is a list of judgments with features filled out. 
* Internally handles getting RankyMcRankFace and writing out judgments to a temp file for training...

### CODE REVIEW

**Comment by softwaredoug** [comment]
Tests pass

```
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
================================================
> WOOHOO!  Tests Passed 👍 For:
commit f32ac3c65e413be753618f899708b93e1da5dc1e
Merge: 538c66c 96cabca
Author: Doug Turnbull <softwaredoug@gmail.com>
Date:   Sat Jun 13 10:55:57 2020 -0400

    Merge branch 'master' into refactor/explicitize-2
================================================
 ===============================================
 HELLO-LTR TEST DETAILS
 Containers Rebuilt? false
 Test Command: tests/run_most_nbs.py
================================================
```

**Review by worleydl — APPROVED** [review]
Looks good to me!

**Comment by nathancday** [comment]
Should we merge this in for LTR class next week?

**Comment by softwaredoug** [comment]
I was going to hold off until after... don't want any surprises!

**Comment by nathancday** [comment]
Cool, I like that.

**Pull request merged**
